### ISSUE TITLE
i'm can'nt add this canvas-designer into my website

### ISSUE THREAD

**Issue by NgocAnPham** [muaz-khan/Canvas-Designer#32]
so i tried to add this canvas to my website by your "How to use" but it not work

**Comment by muaz-khan** [comment]
Download these three files:

1. [canvas-designer-widget.js](https://github.com/muaz-khan/Canvas-Designer/blob/master/canvas-designer-widget.js)
2. [widget.min.js](https://github.com/muaz-khan/Canvas-Designer/blob/master/widget.min.js)
3. [widget.html](https://github.com/muaz-khan/Canvas-Designer/blob/master/widget.html)

Now try this HTML:

````html
<!-- 1st step -->
<script src="canvas-designer-widget.js"></script>

<!-- 2nd step -->
<script>
var designer = new CanvasDesigner();

// both links are mandatory
// widget.html will internally use widget.js
designer.widgetHtmlURL = 'widget.html'; // from your own server
designer.widgetJsURL = 'widget.min.js'; // from your own server
</script>

<!-- 3rd i.e. last step -->
<script>
// <iframe> will be appended to "document.body"
designer.appendTo(document.body || document.documentElement);
</script>
```

**Comment by NgocAnPham** [comment]
ok thanks you!
